# Generated by Django 3.1.7 on 2022-03-05 18:23

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('file_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('files', models.FileField(upload_to='')),
                ('filename', models.TextField(default='file', verbose_name='file name')),
                ('uploaded_date', models.DateTimeField(auto_now_add=True, verbose_name='upload date')),
                ('uploaded_by', models.CharField(max_length=15)),
                ('file_key', models.UUIDField(default=uuid.UUID('1feea1b5-f779-4d30-8b89-3fee7466698e'), unique=True, verbose_name='file id')),
            ],
        ),
    ]
