# Generated by Django 3.1.7 on 2022-03-05 18:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('file_app', '0002_filedetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filedetails',
            name='file_key',
            field=models.UUIDField(default=uuid.UUID('bc5e313a-63e4-4dd2-b02b-a766c87a9613'), unique=True, verbose_name='file id'),
        ),
    ]
