# Generated by Django 3.1.7 on 2022-03-06 05:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('file_app', '0003_auto_20220306_0003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filedetails',
            name='file_key',
            field=models.UUIDField(default=uuid.UUID('0b7910d5-0978-4f03-b0c7-29acf3001f32'), unique=True, verbose_name='file id'),
        ),
    ]
