# Generated by Django 3.1.7 on 2022-03-06 11:34

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('file_app', '0006_auto_20220306_1336'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdetails',
            old_name='files_keys',
            new_name='received_files_keys',
        ),
        migrations.AlterField(
            model_name='filedetails',
            name='file_key',
            field=models.UUIDField(default=uuid.UUID('3f464f77-bdf2-4b7a-bb98-50382cc06611'), unique=True, verbose_name='file id'),
        ),
    ]
