# Generated by Django 3.1.7 on 2022-03-07 07:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('file_app', '0007_auto_20220306_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filedetails',
            name='file_key',
            field=models.UUIDField(default=uuid.UUID('09dd48b0-266e-4f25-8309-93eaa5ac36ab'), unique=True, verbose_name='file id'),
        ),
    ]
