# Generated by Django 3.1.7 on 2022-03-07 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_app', '0009_auto_20220307_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filedetails',
            name='file_key',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, unique=True, verbose_name='file id'),
        ),
    ]
