# Generated by Django 3.1.7 on 2022-03-07 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_app', '0010_auto_20220307_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='received_files_keys',
            field=models.TextField(default='', verbose_name='file keys'),
        ),
    ]
